<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2</name>
   <tag></tag>
   <elementGuidId>e7ca85ef-fce4-4c3b-8b27-0a817ba36366</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='QuickLinks']/a[3]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(3) > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#QuickLinks >> internal:role=link >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6f8233d7-f157-456b-9dea-66322e80bfdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../images/sm_reptiles.gif</value>
      <webElementGuid>fa675873-9799-4e78-8d62-6a88c05876b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;QuickLinks&quot;)/a[3]/img[1]</value>
      <webElementGuid>a24717b6-089c-421d-a355-29feeb8cedaa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='QuickLinks']/a[3]/img</value>
      <webElementGuid>c24f3e44-0484-45f6-ab8f-b62efd043912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/img</value>
      <webElementGuid>2e07c3ee-ff6b-4e0c-b2c7-84c4d1a4651a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../images/sm_reptiles.gif']</value>
      <webElementGuid>92305281-78b0-42f1-ab8a-46fda4f77f83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
